<?xml version="1.0" encoding="UTF-8"?>
<!--
The following XML document is a "digital artifact" containing an XML element ("features") that 
identifies every optional language feature defined in ("used in") ISO/IEC 39075. 
An XML DTD is provided that may be used to validate the XML document itself. 

It may be used by implementers to specify the natural-language text that describes the features
implemented in a particular GQL-implementation.  
It may also be used by documentation writers and translators to identify those features in the 
natural languages of users of those GQL-implementations.
-->


 
<!DOCTYPE features [
  
<!-- The features element defines the features of a standard (part). -->
<!ELEMENT features ((feature)*)>

<!-- A feature element defines a specific feature. -->
<!ELEMENT feature (code, description, implies?)>

<!-- A code element specifies the unique code for a feature. -->
<!ELEMENT code (#PCDATA)>

<!-- A description element provides a textual specification of the feature. -->
<!ELEMENT description (#PCDATA | squote)*>

<!-- An implies element provides a set of implied features. -->
<!ELEMENT implies (impliedFeature | atLeastOneOf)*>

<!-- A code element specifies the unique code for a feature. -->
<!ELEMENT impliedFeature (#PCDATA)>

<!-- An atLeastOneOf element provides a set of implied features where only one is required. -->
<!ELEMENT atLeastOneOf (impliedFeature, (impliedFeature)+)>

]>

<features>
   <feature>
      <code>G002</code>
      <description>Different-edges match mode</description>
   </feature>
   <feature>
      <code>G003</code>
      <description>Explicit REPEATABLE ELEMENTS keyword</description>
   </feature>
   <feature>
      <code>G004</code>
      <description>Path variables</description>
   </feature>
   <feature>
      <code>G005</code>
      <description>Path search prefix in a path pattern</description>
   </feature>
   <feature>
      <code>G006</code>
      <description>Graph pattern KEEP clause: path mode prefix</description>
   </feature>
   <feature>
      <code>G007</code>
      <description>Graph pattern KEEP clause: path search prefix</description>
   </feature>
   <feature>
      <code>G010</code>
      <description>Explicit WALK keyword</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G006</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G011</code>
      <description>Advanced path modes: TRAIL</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G006</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G012</code>
      <description>Advanced path modes: SIMPLE</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G006</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G013</code>
      <description>Advanced path modes: ACYCLIC</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G006</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G014</code>
      <description>Explicit PATH/PATHS keywords</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G006</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G015</code>
      <description>All path search: explicit ALL keyword</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G016</code>
      <description>Any path search</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G017</code>
      <description>All shortest path search</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G018</code>
      <description>Any shortest path search</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G019</code>
      <description>Counted shortest path search</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G020</code>
      <description>Counted shortest group search</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>G005</impliedFeature>
            <impliedFeature>G007</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>G030</code>
      <description>Path multiset alternation</description>
   </feature>
   <feature>
      <code>G031</code>
      <description>Path multiset alternation: variable length path operands</description>
      <implies>
         <impliedFeature>G030</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G032</code>
      <description>Path pattern union</description>
   </feature>
   <feature>
      <code>G033</code>
      <description>Path pattern union: variable length path operands</description>
      <implies>
         <impliedFeature>G032</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G035</code>
      <description>Quantified paths</description>
   </feature>
   <feature>
      <code>G036</code>
      <description>Quantified edges</description>
   </feature>
   <feature>
      <code>G037</code>
      <description>Questioned paths</description>
   </feature>
   <feature>
      <code>G038</code>
      <description>Parenthesized path pattern expression</description>
   </feature>
   <feature>
      <code>G039</code>
      <description>Simplified path pattern expression: full defaulting</description>
      <implies>
         <impliedFeature>G080</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G041</code>
      <description>Non-local element pattern predicates</description>
      <implies>
         <impliedFeature>G051</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G043</code>
      <description>Complete full edge patterns</description>
   </feature>
   <feature>
      <code>G044</code>
      <description>Basic abbreviated edge patterns</description>
   </feature>
   <feature>
      <code>G045</code>
      <description>Complete abbreviated edge patterns</description>
      <implies>
         <impliedFeature>G044</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G046</code>
      <description>Relaxed topological consistency: adjacent vertex patterns</description>
   </feature>
   <feature>
      <code>G047</code>
      <description>Relaxed topological consistency: concise edge patterns</description>
   </feature>
   <feature>
      <code>G048</code>
      <description>Parenthesized path pattern: subpath variable declaration</description>
      <implies>
         <impliedFeature>G038</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G049</code>
      <description>Parenthesized path pattern: path mode prefix</description>
      <implies>
         <impliedFeature>G038</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G050</code>
      <description>Parenthesized path pattern: WHERE clause</description>
      <implies>
         <impliedFeature>G038</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G051</code>
      <description>Parenthesized path pattern: non-local predicates</description>
      <implies>
         <impliedFeature>G050</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G060</code>
      <description>Bounded graph pattern quantifiers</description>
   </feature>
   <feature>
      <code>G061</code>
      <description>Unbounded graph pattern quantifiers</description>
      <implies>
         <impliedFeature>G060</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G074</code>
      <description>Label expression: wildcard label</description>
   </feature>
   <feature>
      <code>G080</code>
      <description>Simplified path pattern expression: basic defaulting</description>
   </feature>
   <feature>
      <code>G081</code>
      <description>Simplified path pattern expression: full overrides</description>
      <implies>
         <impliedFeature>G082</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G082</code>
      <description>Simplified path pattern expression: basic overrides</description>
      <implies>
         <impliedFeature>G080</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>G100</code>
      <description>ELEMENT_ID function</description>
   </feature>
   <feature>
      <code>G110</code>
      <description>IS DIRECTED predicate</description>
   </feature>
   <feature>
      <code>G111</code>
      <description>IS LABELED predicate</description>
   </feature>
   <feature>
      <code>G112</code>
      <description>IS SOURCE and IS DESTINATION predicate</description>
   </feature>
   <feature>
      <code>G113</code>
      <description>ALL_DIFFERENT predicate</description>
   </feature>
   <feature>
      <code>G114</code>
      <description>SAME predicate</description>
   </feature>
   <feature>
      <code>G115</code>
      <description>PROPERTY_EXISTS predicate</description>
   </feature>
   <feature>
      <code>GA01</code>
      <description>IEEE 754 floating point operations</description>
   </feature>
   <feature>
      <code>GA03</code>
      <description>Explicit ordering of nulls</description>
   </feature>
   <feature>
      <code>GA04</code>
      <description>Universal comparison</description>
      <implies>
         <impliedFeature>GA09</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GA05</code>
      <description>Cast specification</description>
   </feature>
   <feature>
      <code>GA06</code>
      <description>Value type predicate</description>
   </feature>
   <feature>
      <code>GA07</code>
      <description>Ordering by discarded binding variables</description>
   </feature>
   <feature>
      <code>GA08</code>
      <description>GQL-status objects with diagnostic records</description>
   </feature>
   <feature>
      <code>GA09</code>
      <description>Comparison of paths</description>
   </feature>
   <feature>
      <code>GB01</code>
      <description>Long identifiers</description>
   </feature>
   <feature>
      <code>GB02</code>
      <description>Double minus sign comments</description>
   </feature>
   <feature>
      <code>GB03</code>
      <description>Double solidus comments</description>
   </feature>
   <feature>
      <code>GC00</code>
      <description>Automatic graph population</description>
   </feature>
   <feature>
      <code>GC01</code>
      <description>Graph schema management</description>
   </feature>
   <feature>
      <code>GC02</code>
      <description>Graph schema management: IF [ NOT ] EXISTS</description>
      <implies>
         <impliedFeature>GC01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GC03</code>
      <description>Graph type: IF [ NOT ] EXISTS</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GC04</code>
      <description>Graph management</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GG01</impliedFeature>
            <impliedFeature>GG02</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GC05</code>
      <description>Graph management: IF [ NOT ] EXISTS</description>
      <implies>
         <impliedFeature>GC04</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GD01</code>
      <description>Updatable graphs</description>
      <implies>
         <impliedFeature>GT01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GD02</code>
      <description>Graph label set changes</description>
      <implies>
         <impliedFeature>GD01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GD03</code>
      <description>DELETE statement: subquery support</description>
      <implies>
         <impliedFeature>GD04</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GD04</code>
      <description>DELETE statement: simple expression support</description>
      <implies>
         <impliedFeature>GD01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GE01</code>
      <description>Graph reference value expressions</description>
      <implies>
         <impliedFeature>GV60</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GE02</code>
      <description>Binding table reference value expressions</description>
      <implies>
         <impliedFeature>GV61</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GE03</code>
      <description>Let-binding of variables in expressions</description>
   </feature>
   <feature>
      <code>GE04</code>
      <description>Graph parameters</description>
      <implies>
         <impliedFeature>GV60</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GE05</code>
      <description>Binding table parameters</description>
      <implies>
         <impliedFeature>GV61</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GE06</code>
      <description>Path value construction</description>
      <implies>
         <impliedFeature>GV55</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GE07</code>
      <description>Boolean XOR</description>
   </feature>
   <feature>
      <code>GE08</code>
      <description>Reference parameters</description>
   </feature>
   <feature>
      <code>GE09</code>
      <description>Horizontal aggregation</description>
   </feature>
   <feature>
      <code>GF01</code>
      <description>Enhanced numeric functions</description>
   </feature>
   <feature>
      <code>GF02</code>
      <description>Trigonometric functions</description>
   </feature>
   <feature>
      <code>GF03</code>
      <description>Logarithmic functions</description>
   </feature>
   <feature>
      <code>GF04</code>
      <description>Enhanced path functions</description>
      <implies>
         <impliedFeature>GV55</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GF05</code>
      <description>Multi-character TRIM function</description>
   </feature>
   <feature>
      <code>GF06</code>
      <description>Explicit TRIM function</description>
   </feature>
   <feature>
      <code>GF07</code>
      <description>Byte string TRIM function</description>
      <implies>
         <impliedFeature>GV35</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GF10</code>
      <description>Advanced aggregate functions: general set functions</description>
   </feature>
   <feature>
      <code>GF11</code>
      <description>Advanced aggregate functions: binary set functions</description>
   </feature>
   <feature>
      <code>GF12</code>
      <description>CARDINALITY function</description>
   </feature>
   <feature>
      <code>GF13</code>
      <description>SIZE function</description>
      <implies>
         <impliedFeature>GV50</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GF20</code>
      <description>Aggregate functions in sort keys</description>
   </feature>
   <feature>
      <code>GG01</code>
      <description>Graph with an open graph type</description>
      <implies>
         <impliedFeature>GC04</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG02</code>
      <description>Graph with a closed graph type</description>
      <implies>
         <impliedFeature>GC04</impliedFeature>
         <atLeastOneOf>
            <impliedFeature>GG20</impliedFeature>
            <impliedFeature>GG21</impliedFeature>
            <impliedFeature>GG22</impliedFeature>
            <impliedFeature>GG23</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GG03</code>
      <description>Graph type inline specification</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG04</code>
      <description>Graph type like a graph</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG05</code>
      <description>Graph from a graph source</description>
      <implies>
         <impliedFeature>GC04</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG20</code>
      <description>Explicit element type names</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG21</code>
      <description>Explicit element type key label sets</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG22</code>
      <description>Element type key label set inference</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG23</code>
      <description>Optional element type key label sets</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG24</code>
      <description>Relaxed structural consistency</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG25</code>
      <description>Relaxed key label set uniqueness for edge types</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GG26</code>
      <description>Relaxed property value type consistency</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GH01</code>
      <description>External object references</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GH02</code>
      <description>Undirected edge patterns</description>
      <implies>
         <impliedFeature>GG02</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GL01</code>
      <description>Hexadecimal literals</description>
   </feature>
   <feature>
      <code>GL02</code>
      <description>Octal literals</description>
   </feature>
   <feature>
      <code>GL03</code>
      <description>Binary literals</description>
   </feature>
   <feature>
      <code>GL04</code>
      <description>Exact number in common notation without suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV01</impliedFeature>
            <impliedFeature>GV02</impliedFeature>
            <impliedFeature>GV03</impliedFeature>
            <impliedFeature>GV04</impliedFeature>
            <impliedFeature>GV05</impliedFeature>
            <impliedFeature>GV06</impliedFeature>
            <impliedFeature>GV07</impliedFeature>
            <impliedFeature>GV08</impliedFeature>
            <impliedFeature>GV10</impliedFeature>
            <impliedFeature>GV11</impliedFeature>
            <impliedFeature>GV12</impliedFeature>
            <impliedFeature>GV13</impliedFeature>
            <impliedFeature>GV14</impliedFeature>
            <impliedFeature>GV15</impliedFeature>
            <impliedFeature>GV16</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL05</code>
      <description>Exact number in common notation or as decimal integer with suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV01</impliedFeature>
            <impliedFeature>GV02</impliedFeature>
            <impliedFeature>GV03</impliedFeature>
            <impliedFeature>GV04</impliedFeature>
            <impliedFeature>GV05</impliedFeature>
            <impliedFeature>GV06</impliedFeature>
            <impliedFeature>GV07</impliedFeature>
            <impliedFeature>GV08</impliedFeature>
            <impliedFeature>GV10</impliedFeature>
            <impliedFeature>GV11</impliedFeature>
            <impliedFeature>GV12</impliedFeature>
            <impliedFeature>GV13</impliedFeature>
            <impliedFeature>GV14</impliedFeature>
            <impliedFeature>GV15</impliedFeature>
            <impliedFeature>GV16</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL06</code>
      <description>Exact number in scientific notation with suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV01</impliedFeature>
            <impliedFeature>GV02</impliedFeature>
            <impliedFeature>GV03</impliedFeature>
            <impliedFeature>GV04</impliedFeature>
            <impliedFeature>GV05</impliedFeature>
            <impliedFeature>GV06</impliedFeature>
            <impliedFeature>GV07</impliedFeature>
            <impliedFeature>GV08</impliedFeature>
            <impliedFeature>GV10</impliedFeature>
            <impliedFeature>GV11</impliedFeature>
            <impliedFeature>GV12</impliedFeature>
            <impliedFeature>GV13</impliedFeature>
            <impliedFeature>GV14</impliedFeature>
            <impliedFeature>GV15</impliedFeature>
            <impliedFeature>GV16</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL07</code>
      <description>Approximate number in common notation or as decimal integer with suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV17</impliedFeature>
            <impliedFeature>GV20</impliedFeature>
            <impliedFeature>GV21</impliedFeature>
            <impliedFeature>GV23</impliedFeature>
            <impliedFeature>GV24</impliedFeature>
            <impliedFeature>GV25</impliedFeature>
            <impliedFeature>GV26</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL08</code>
      <description>Approximate number in scientific notation with suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV17</impliedFeature>
            <impliedFeature>GV20</impliedFeature>
            <impliedFeature>GV21</impliedFeature>
            <impliedFeature>GV23</impliedFeature>
            <impliedFeature>GV24</impliedFeature>
            <impliedFeature>GV25</impliedFeature>
            <impliedFeature>GV26</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL09</code>
      <description>Optional float number suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV17</impliedFeature>
            <impliedFeature>GV20</impliedFeature>
            <impliedFeature>GV21</impliedFeature>
            <impliedFeature>GV23</impliedFeature>
            <impliedFeature>GV24</impliedFeature>
            <impliedFeature>GV25</impliedFeature>
            <impliedFeature>GV26</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL10</code>
      <description>Optional double number suffix</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GV17</impliedFeature>
            <impliedFeature>GV20</impliedFeature>
            <impliedFeature>GV21</impliedFeature>
            <impliedFeature>GV23</impliedFeature>
            <impliedFeature>GV24</impliedFeature>
            <impliedFeature>GV25</impliedFeature>
            <impliedFeature>GV26</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GL11</code>
      <description>Opt-out character escaping</description>
   </feature>
   <feature>
      <code>GL12</code>
      <description>SQL datetime and interval formats</description>
      <implies>
         <impliedFeature>GV39</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP01</code>
      <description>Inline procedure</description>
      <implies>
         <atLeastOneOf>
            <impliedFeature>GP02</impliedFeature>
            <impliedFeature>GP03</impliedFeature>
         </atLeastOneOf>
      </implies>
   </feature>
   <feature>
      <code>GP02</code>
      <description>Inline procedure with implicit nested variable scope</description>
      <implies>
         <impliedFeature>GP01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP03</code>
      <description>Inline procedure with explicit nested variable scope</description>
      <implies>
         <impliedFeature>GP01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP04</code>
      <description>Named procedure calls</description>
   </feature>
   <feature>
      <code>GP05</code>
      <description>Procedure-local value variable definitions</description>
      <implies>
         <impliedFeature>GP17</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP06</code>
      <description>Procedure-local value variable definitions: value variables based on simple expressions</description>
      <implies>
         <impliedFeature>GP05</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP07</code>
      <description>Procedure-local value variable definitions: value variable based on subqueries</description>
      <implies>
         <impliedFeature>GP05</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP08</code>
      <description>Procedure-local binding table variable definitions</description>
      <implies>
         <impliedFeature>GP17</impliedFeature>
         <impliedFeature>GV61</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP09</code>
      <description>Procedure-local binding table variable definitions: binding table variables based on simple expressions or references</description>
      <implies>
         <impliedFeature>GP08</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP10</code>
      <description>Procedure-local binding table variable definitions: binding table variables based on subqueries</description>
      <implies>
         <impliedFeature>GP08</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP11</code>
      <description>Procedure-local graph variable definitions</description>
      <implies>
         <impliedFeature>GP17</impliedFeature>
         <impliedFeature>GV60</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP12</code>
      <description>Procedure-local graph variable definitions: graph variables based on simple expressions or references</description>
      <implies>
         <impliedFeature>GP11</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP13</code>
      <description>Procedure-local graph variable definitions: graph variables based on subqueries</description>
      <implies>
         <impliedFeature>GP11</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP14</code>
      <description>Binding tables as procedure arguments</description>
      <implies>
         <impliedFeature>GP04</impliedFeature>
         <impliedFeature>GV61</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP15</code>
      <description>Graphs as procedure arguments</description>
      <implies>
         <impliedFeature>GP04</impliedFeature>
         <impliedFeature>GV60</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GP16</code>
      <description>AT schema clause</description>
   </feature>
   <feature>
      <code>GP17</code>
      <description>Binding variable definition block</description>
   </feature>
   <feature>
      <code>GP18</code>
      <description>Catalog and data statement mixing</description>
      <implies>
         <impliedFeature>GC04</impliedFeature>
         <impliedFeature>GD01</impliedFeature>
      </implies>
   </feature>
   <feature>
      <code>GQ01</code>
      <description>USE graph clause</description>
   </feature>
   <feature>
      <code>GQ02</code>
      <description>Composite query: OTHERWISE</description>
   </feature>
   <feature>
      <code>GQ03</code>
      <description>Composite query: UNION</description>
   </feature>
   <feature>
      <code>GQ04</code>
      <description>Composite query: EXCEPT DISTINCT</description>
   </feature>
   <feature>
      <code>GQ05</code>
      <description>Composite query: EXCEPT ALL</description>
      <implies>